### ISSUE TITLE
Deploy new version including the PR #4 on pypi

### ISSUE THREAD

**Issue by tracim** [gasbasd/tgapp-resetpassword#5]
Hello,

The following PR https://github.com/gasbasd/tgapp-resetpassword/pull/4 has been merge in january. It is unfortunatelly not available on pypi. Is it possible to deploy a new relase of tgapp-resetpassword on pypi ?

Thanks

**Comment by amol-** [comment]
Released as 0.2.0 https://pypi.python.org/pypi/tgapp-resetpassword
Moved primary repository to https://github.com/axant/tgapp-resetpassword as this one was no longer maintained.

**Comment by lebouquetin** [comment]
Hi amol, the pypi page https://pypi.python.org/pypi/tgapp-resetpassword makes reference to https://github.com/gasbasd/tgapp-resetpassword instead of the new primary repo.

I created a PR for updated setup.py.
